<section class="content">
    <header class="content__title">
        <h1>CREATE MEMO</h1>

        <div class="actions">
                <a href="" class="actions__item zmdi zmdi-trending-up"></a>
                <a href="" class="actions__item zmdi zmdi-check-all"></a>

                <div class="dropdown actions__item">
                    <i data-toggle="dropdown" class="zmdi zmdi-more-vert"></i>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a href="<?php echo base_url() ?>memo/create" class="dropdown-item">Refresh</a>
                    </div>
                </div>
            </div>
    </header>

    <div class="card">
        <div class="card-header">
            <h2 class="card-title">New Memo</h2>
            <small class="card-subtitle">Please make sure you're fill all data correctly. Thank you!</small>
        </div>

        <div class="card-block">
            <?php 
                $rand   = rand(000,999);
            ?>
            <form action="<?php echo base_url() ?>memo/creatememo" method="post" id="formaddmemo">
                <div class="row">
                    <div class="col-sm-8">
                        <div class="form-group form-group--float">
                            <input type="text" class="form-control" name="namamemo" id="namamemo" required title="Tidak boleh kosong." rel="tooltip">
                            <label>Nama Memo <a class="text-danger"> *</a></label>
                            <i class="form-group__bar"></i>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group form-group--float">
                            <input type="text" class="form-control" name="nomemo" title="generated automatically." rel="tooltip"  value="<?php echo $nomemo; ?>" readonly>
                            <label>No Memo<a class="text-success"><small> (generated by system)</small></a></label>
                            <i class="form-group__bar"></i>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-5">
                        <div class="form-group">
                            <label>Kepada</label>
                            <select class="select2" name="kepada[]" multiple data-placeholder="Pilih satu atau lebih bagian." required>
                                <option value="Blown Film">Blown Film</option>
                                <option value="CPP">CPP</option>
                                <option value="Metalize">Metalize</option>
                                <option value="PCM">PCM</option>
                                <option value="PL 1 PRINTING">PL 1 PRINTING</option>
                                <option value="PL 1 Laminasi">PL 1 Laminasi</option>
                                <option value="PL 1 Extrusion">PL 1 Extrusion</option>
                                <option value="PL 1 Slitter">PL 1 Slitter</option>
                                <option value="PL 1 Bag Making">PL 1 Bag Making</option>
                                <option value="PL 2 Laminasi">PL 2 Laminasi</option>
                                <option value="PL 2 PRINTING">PL 2 PRINTING</option>
                                <option value="PL 2 SLITTER">PL 2 SLITTER</option>
                                <option value="PL 3 Printing">PL 3 Printing</option>
                                <option value="PL 3 Laminasi">PL 3 Laminasi</option>
                                <option value="PL 3 Extrusion">PL 3 Extrusion</option>
                                <option value="PL 3 Slitter">PL 3 Slitter</option>
                                <option value="Warehouse">Warehouse</option>
                                <option value="PRINTING PHARMA">PRINTING PHARMA</option>
                                <option value="EXTRUSION PHARMA">EXTRUSION PHARMA</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-7">
                        <div class="form-group form-group--float">
                            <input type="text" class="form-control" title="Tidak boleh kosong." rel="tooltip" name="hal" required>
                            <label>Perihal <a class="text-danger"> *</a></label>
                            <i class="form-group__bar"></i>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <label>Isi Memo</label>
                        <textarea name="content" id="editor1"></textarea>
                    </div>
                </div><br>

                <div class="row">
                    <div class="col-md-3">
                        <h3>
                            <small>Mengetahui:</small>
                        </h3>
                        <a class="text-danger"><small> *Kosongkan jika tidak perlu.</small></a><br>
                        <a class="text-danger"><small> *Kadiv wajib di isi / tidak boleh kosong!</small></a>
                    </div>
                </div>

                <br>

                <div class="row">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>QC <a class="text-success"><small>(pilih)</small></a></label>
                            <select class="select2" name="appqc" title="Pilih Approval QC." rel="tooltip" data-placeholder="Pilih Approval QC.">
                                <option value="">-- PILIH --</option>
                                <option value="0">KOSONGKAN APPROVER QC</option>
                                <?php foreach ($getQC as $s) {
                                    # code...
                                    echo '<option value="'.$s['nama'].'">'.$s['nama'].'</option>';
                                } 
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>R&D <a class="text-success"><small>(pilih)</small></a></label>
                            <select class="select2" name="apprnd" title="Pilih Approval R&D." rel="tooltip" data-placeholder="Pilih Approval R&D.">
                                <option value="">-- PILIH --</option>
                                <option value="0">KOSONGKAN APPROVER R&D</option>
                                <?php foreach ($getRND as $s) {
                                    # code...
                                    echo '<option value="'.$s['nama'].'">'.$s['nama'].'</option>';
                                } 
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Produksi / Kadiv <a class="text-success"><small>(pilih)</small></a><a class="text-danger">*</a></label>
                            <select class="select2" name="appproduksi" title="Pilih Approval PRODUKSI." rel="tooltip" data-placeholder="Pilih Approval Produksi." required>
                                <option value="">-- PILIH --</option>
                                <?php foreach ($getProduksi as $s) {
                                    # code...
                                    echo '<option value="'.$s['nama'].'">'.$s['nama'].'</option>';
                                } 
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Accounting <a class="text-info"><small>(optional)</small></a></label>
                            <select class="select2" name="appacc" title="Pilih Approval ACCOUNTING." rel="tooltip" data-placeholder="Pilih Approval Accounting(Optional).">
                                <option value="">-- PILIH --</option>
                                <option value="0">KOSONGKAN APPROVER ACCOUNTING</option>
                                <?php foreach ($getAccounting as $s) {
                                    # code...
                                    echo '<option value="'.$s['nama'].'">'.$s['nama'].'</option>';
                                } 
                                ?>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>PPIC <a class="text-success"><small>(pilih)</small></a><a class="text-danger">*</a></label></label>
                            <select class="select2" name="app_ppic" title="Pilih Approval PPIC." rel="tooltip" data-placeholder="Pilih Approval PPIC." required>
                                <option value="">-- PILIH --</option>
                                <?php foreach ($getPPIC as $s) {
                                    # code...
                                    echo '<option value="'.$s['nama'].'">'.$s['nama'].'</option>';
                                } 
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-3"></div><div class="col-sm-3"></div>
                    <div class="col-sm-3">
                        <div class="form-group form-group--float">
                            <input type="text" class="form-control" name="oleh" value="<?php echo $section; ?>" readonly>
                            <label>Dibuat Oleh<a class="text-info"><small> (readonly)</small></a></label>
                            <i class="form-group__bar"></i>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <label>Keterangan <a class="text-danger">*</a></label>
                        <div class="form-group">
                            <textarea class="form-control textarea-autosize" name="keterangan" placeholder="Tuliskan keterangan memo untuk disampaikan kepada approver." required></textarea>
                            <i class="form-group__bar"></i>
                        </div>
                    </div>
                </div>
                <br><br>
                
                <div class="row">
                    <div class="col-md-12">
                        <a href="<?php echo base_url() ?>memo" class="btn btn-md btn-danger btn--icon-text text-whitepull pull-right"><i class="zmdi zmdi-arrow-back"></i> Back</a><a class="pull-right"> &nbsp; </a>
                        <button name="addmemo" id="addmemo" class="btn btn-md btn-success btn--icon-text text-white pull-right monitored-btn"><i class="zmdi zmdi-save"></i> Save</button>
                        <div id="loadingheader">
                            <button name="addmemo" id="addmemo" class="btn btn-md btn-success btn--icon-text text-white pull-right" disabled><i class="zmdi zmdi-save"></i> Please wait..</button>
                        </div>
                    </div>
                </div>
            </form>
            <br><br><br>
        </div>
    </div>
